version: "3"

services:
  react-app:
    container_name: myfrontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
