version: "3.8"

services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myfrontend
    ports:
      - "3000:3000" # Host:Container
    volumes:
      - .:/app        # Mount current dir to container
      - /app/node_modules # Prevent overwriting node_modules
    stdin_open: true
    tty: true
