version: "3"

services:
  react-app:
    image: ankurdwivedi/expensetracker:latest
    container_name: expensetracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
