version: "3"

services:
  react-app:
    image: ankurdwivedi/expensetracker-frontend:latest
    container_name: expensetracker
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
