version: "3.8"
services:
    mongodb:
        image: 'mongo'
        container_name: mymongodb
        ports:
          - '27017:27017'
        volumes: 
            - data:/data/db

    backend:
        image: ankurdwivedi/expensetracker-backend
        container_name: mybackend
        ports:
            - '4000:4000'
        env_file:
             - ./.env.backend
        depends_on:
            - mongodb
    react-app:
        image: ankurdwivedi/expensetracker-frontend:latest
        container_name: expensetracker
        ports:
            - "3000:80"
        depends_on:
            - backend
        restart: always
volumes:
    data: