version: "3.8"
services:
    mongodb:
        image: 'mongo'
        container_name: mymongodb
        ports:
          - '27017:27017'
        volumes: 
            - data:/data/db

    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: mybackend
        ports:
            - '4000:4000'
        volumes:
            - .:/app    
            - /app/node_modules 
        env_file:
             - ./.env
        depends_on:
            - mongodb
volumes:
    data: